"""Turn this repository's own history into raw sources for an llm-wiki.

A wiki administrator reads ordinary files, so every source becomes one markdown
file with a stable name. The manifest records a digest per file: a schema that
keeps a ledger of processed sources compares against it instead of reasoning
about what is new, which is the difference between a lookup and a judgement.

The command line lives in `tools/export_history.py`; everything testable lives
here, where the offline suite reaches it.
"""

from __future__ import annotations

import json
import re
import subprocess
from collections.abc import Iterable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from workbench.envelope import sha256

# Documents worth keeping as sources. Generated trees, workspace fixtures and
# the archived C# stand itself are deliberately absent: the wiki is about how
# this project decided things, not about what it compiled.
DOCUMENT_GLOBS = (
    "VISION.md",
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "README.ru.md",
    "docs/*.md",
    "docs/decisions/*.md",
    "docs/design/*.md",
    "archive/prototype-r4.2/docs/decisions/*.md",
    "archive/prototype-r4.2/docs/research/*.md",
)

# A commit whose diff exceeds this keeps its message and file list; the body is
# truncated with an explicit marker rather than silently shortened.
DEFAULT_DIFF_LIMIT = 8_000

# Wrappers Claude Code puts around slash commands and injected context. They are
# harness plumbing, not something anyone said, and they drown the real turns.
NOISE_PATTERNS = (
    re.compile(r"<local-command-[^>]*>.*?</local-command-[^>]*>", re.S),
    re.compile(r"<command-(name|message|args)>.*?</command-(name|message|args)>", re.S),
    re.compile(r"<system-reminder>.*?</system-reminder>", re.S),
    re.compile(r"^Caveat: The messages below were generated by the user.*$", re.M),
)

# A bare slash command instructs the harness rather than continuing the
# conversation, and an acknowledgement of one carries nothing.
SLASH_COMMAND = re.compile(r"^/[a-z][a-z0-9:-]*(\s.*)?$", re.S)
EMPTY_REPLIES = frozenset({"No response requested.", "(no content)"})
TOOL_MARKER = re.compile(r"^_\(вызов инструмента: [^)]*\)_$")


def slugify(text: str, limit: int = 72) -> str:
    """A stable, lowercase, filesystem-safe name for a source.

    Truncation stops at a word boundary: a name cut mid-word reads as damage
    rather than as shortening, and these names are what the wiki cites.
    """
    lowered = text.lower().replace("ё", "е")
    cleaned = re.sub(r"[^a-z0-9а-я]+", "-", lowered).strip("-")
    if len(cleaned) > limit:
        cleaned = cleaned[:limit].rsplit("-", 1)[0]
    return cleaned.strip("-") or "untitled"


def document_name(relative: Path) -> str:
    """Name a document by what it is, not by where it sits on disk."""
    stem = slugify(relative.stem)
    parents = {part.lower() for part in relative.parts[:-1]}
    prefix = "archive-" if "archive" in parents else ""
    for marker, label in (("decisions", "adr"), ("design", "design"), ("research", "research")):
        if marker in parents:
            return f"{prefix}{label}-{stem}.md"
    return f"{prefix}{stem}.md"


def git(repository: Path, *arguments: str) -> str:
    """Read-only git call against a repository."""
    result = subprocess.run(
        ["git", "-C", str(repository), *arguments],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def write_source(
    directory: Path, name: str, body: str, kind: str, origin: str
) -> dict[str, Any]:
    """Write one source file and describe it for the manifest."""
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / name
    path.write_text(body, encoding="utf-8")
    return {
        "path": str(path.relative_to(directory.parent)),
        "kind": kind,
        "origin": origin,
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
    }


def export_documents(repository: Path, output: Path) -> list[dict[str, Any]]:
    """Copy the project's own prose, flattened into one directory."""
    entries: list[dict[str, Any]] = []
    for pattern in DOCUMENT_GLOBS:
        for source in sorted(repository.glob(pattern)):
            if not source.is_file():
                continue
            relative = source.relative_to(repository)
            header = f"<!-- источник: {relative} -->\n\n"
            entries.append(
                write_source(
                    output / "documents",
                    document_name(relative),
                    header + source.read_text(encoding="utf-8"),
                    "document",
                    str(relative),
                )
            )
    return entries


def export_commits(
    repository: Path, output: Path, diff_limit: int = DEFAULT_DIFF_LIMIT
) -> list[dict[str, Any]]:
    """One file per commit: message, changed files, and the diff itself."""
    entries: list[dict[str, Any]] = []
    for revision in git(repository, "log", "--reverse", "--pretty=format:%H").split():
        short, date, subject, body = git(
            repository,
            "show",
            "--no-patch",
            "--pretty=format:%h%n%ad%n%s%n%b",
            "--date=short",
            revision,
        ).split("\n", 3)
        stat = git(repository, "show", "--stat", "--format=", revision).strip()
        diff = git(repository, "show", "--format=", "--no-color", revision)
        truncated = ""
        if len(diff) > diff_limit:
            diff = diff[:diff_limit]
            truncated = f"\n...\n(дифф обрезан на {diff_limit} байтах)\n"
        text = (
            f"# Коммит {short}: {subject}\n\n"
            f"**Дата**: {date}\n"
            f"**Полный хеш**: {revision}\n\n"
            f"{body.strip()}\n\n"
            f"## Затронутые файлы\n\n```\n{stat}\n```\n\n"
            f"## Изменения\n\n```diff\n{diff}{truncated}```\n"
        )
        entries.append(
            write_source(
                output / "commits",
                f"{date}-{short}-{slugify(subject)}.md",
                text,
                "commit",
                revision,
            )
        )
    return entries


def readable_blocks(content: Any) -> Iterable[str]:
    """Human-readable parts of one transcript message.

    Tool results are dropped and tool calls collapse to a single line: the wiki
    is about what was said and decided, not about every file that was read.
    """
    if isinstance(content, str):
        yield content
        return
    if not isinstance(content, list):
        return
    for block in content:
        if not isinstance(block, dict):
            continue
        if block.get("type") == "text":
            yield block.get("text", "")
        elif block.get("type") == "tool_use":
            yield f"_(вызов инструмента: {block.get('name', '?')})_"


def strip_noise(text: str) -> str:
    """Remove harness wrappers that were never part of the conversation."""
    for pattern in NOISE_PATTERNS:
        text = pattern.sub("", text)
    return text.strip()


def spoken_turn(record: dict[str, Any]) -> tuple[str, str] | None:
    """The day and rendered text of one transcript entry, if a person or the
    assistant actually said something in it."""
    kind = record.get("type")
    if kind not in ("user", "assistant") or record.get("isSidechain"):
        return None
    # A compaction summary is written by the harness about the conversation;
    # keeping it would attribute it to whoever spoke last and duplicate the
    # turns it summarises.
    if record.get("isCompactSummary") or record.get("isVisibleInTranscriptOnly"):
        return None
    message = record.get("message") or {}
    text = strip_noise("\n".join(readable_blocks(message.get("content"))))
    if not text or text in EMPTY_REPLIES:
        return None
    if kind == "user" and len(text) < 200 and SLASH_COMMAND.match(text):
        return None
    # A turn that is nothing but tool calls says only that work happened; the
    # prose turns say what it decided.
    if all(TOOL_MARKER.match(part) for part in text.splitlines() if part.strip()):
        return None
    day = str(record.get("timestamp", ""))[:10] or "undated"
    speaker = "Владелец" if kind == "user" else "Claude"
    return day, f"### {speaker}\n\n{text}\n"


def export_conversations(output: Path, transcripts: Path) -> list[dict[str, Any]]:
    """One file per session and day: a whole session is too big to ingest."""
    entries: list[dict[str, Any]] = []
    if not transcripts.is_dir():
        return entries
    for path in sorted(transcripts.glob("*.jsonl")):
        by_day: dict[str, list[str]] = {}
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            turn = spoken_turn(record)
            if turn is None:
                continue
            by_day.setdefault(turn[0], []).append(turn[1])
        session = path.stem.split("-")[0]
        for day, turns in sorted(by_day.items()):
            if len(turns) < 2:
                continue
            text = f"# Разговор {day} ({session})\n\n" + "\n".join(turns)
            entries.append(
                write_source(
                    output / "conversations",
                    f"{day}-{session}.md",
                    text,
                    "conversation",
                    f"{path.name}#{day}",
                )
            )
    return entries


def write_manifest(
    repository: Path, output: Path, entries: list[dict[str, Any]]
) -> Path:
    """Record what was exported, so a ledger can be compared against it."""
    manifest = {
        "exported_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "repository": str(repository),
        "commit": git(repository, "rev-parse", "HEAD").strip(),
        "digest_method": "sha256-file-bytes",
        "sources": entries,
    }
    path = output / "MANIFEST.json"
    path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path
